apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: kube-prometheus-stack-system
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cert-manager-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: cert-manager
  endpoints:
    - port: tcp-prometheus-servicemonitor
      interval: 30s
    - port: http-metrics
      interval: 30s
    - port: metrics
      interval: 30s
