apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-controllers
  namespace: kube-prometheus-stack-system
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: flux-system
      app.kubernetes.io/part-of: flux
  podMetricsEndpoints:
    - port: http-prom
      interval: 30s
