persistence:
  defaultClass: false
longhornUI:
  replicas: 1
defaultSettings:
  storageMinimalAvailablePercentage: 5
  defaultReplicaCount: 1
defaultBackupStore:
  backupTarget: s3://tinyrack-prod@hetzner/clusters/public/longhorn
  backupTargetCredentialSecret: tinyrack-s3-secret
