kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  dataLocality: strict-local
  numberOfReplicas: "1"
