---
restore_sealed_secrets_key_namespace: sealed-secrets
restore_sealed_secrets_key_ready_timeout: 300s
restore_sealed_secrets_key_public_cert_path: "{{ playbook_dir }}/../../tinyrack-production-key.crt"
restore_sealed_secrets_key_resources: "{{ vault_sealed_secrets_key_resources }}"
