apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-crds
  namespace: flux-system
spec:
  interval: 15m
  path: ./flux/infrastructure/base/longhorn/crds
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn-install
