---
creation_rules:
  - path_regex: "talos/.+"
    encrypted_regex: "secrets?|ca|crt|key|token|serviceAccount"
    key_groups:
      - age:
        - "age13sfv0zxnqzs8vysk3j9fwcf7fpg94u6v27wg22tsp6ygkv5pu4gqjfrc7f"
