apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy-release
  namespace: flux-system
spec:
  targetNamespace: observability-system
  storageNamespace: observability-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: alloy
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: alloy
  values:
    crds:
      create: false
    alloy:
      configMap:
        content: |
          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "pod_logs" {
            targets = discovery.kubernetes.pods.targets

            rule {
              target_label = "cluster"
              replacement  = "mail-server"
            }

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app"]
              regex         = "(.+)"
              target_label  = "app"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
              regex         = "(.+)"
              target_label  = "app"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
              separator     = "/"
              target_label  = "__path__"
              replacement   = "/var/log/pods/*$1/*.log"
            }
          }

          local.file_match "pod_logs" {
            path_targets = discovery.relabel.pod_logs.output
          }

          loki.source.file "pod_logs" {
            targets       = local.file_match.pod_logs.targets
            tail_from_end = true
            forward_to    = [loki.process.pod_logs.receiver]
          }

          loki.process "pod_logs" {
            stage.cri {}

            forward_to = [loki.write.default.receiver]
          }

          loki.write "default" {
            endpoint {
              url = "http://loki.observability-system.svc.cluster.local:3100/loki/api/v1/push"
            }
          }
      enableReporting: false
      mounts:
        varlog: true
    controller:
      type: daemonset
    ingress:
      enabled: false
    rbac:
      create: true
    serviceAccount:
      create: true
