apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-snapshot-cleanup
  namespace: longhorn-system
spec:
  task: snapshot-cleanup
  concurrency: 2
  cron: "0 5 * * *"
  retain: 0
  groups:
    - default
