apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-volume-backup
  namespace: longhorn-system
spec:
  task: backup
  cron: "30 3,15 * * *"
  retain: 14
  concurrency: 2
  groups:
    - longhorn-backup
