apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-install
  namespace: flux-system
spec:
  interval: 15m
  path: ./flux/infrastructure/base/longhorn/install
  prune: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
