---
all:
  children:
    k3s_servers:
      hosts:
        mail-server:
          ansible_host: mail-server
          ansible_user: winetree94
          ansible_become_password: "{{ vault_mail_server_become_password }}"
