apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 5m
  timeout: 10m
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
      valuesKey: values.yaml
