cluster:
  name: mail-server
  id: 0
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443
kubeProxyReplacement: true
identityAllocationMode: crd
operator:
  replicas: 1
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.57.0.0/16
    clusterPoolIPv4MaskSize: 24
routingMode: tunnel
tunnelProtocol: vxlan
bpf:
  masquerade: true
egressGateway:
  enabled: true
devices: eth0
hostFirewall:
  enabled: true
cni:
  exclusive: true
  uninstall: false
policyEnforcementMode: default
hubble:
  enabled: false
