apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bulwark-data
  namespace: bulwark-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    recurring-job-group.longhorn.io/longhorn-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-strict-local
  volumeMode: Filesystem
