---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bulwark-secrets
  namespace: bulwark-system
spec:
  encryptedData:
    SESSION_SECRET: AgCDVtbTECP/cJ6jUDVoplqesJicLAvIHAwouYrf5Gi+PAHbEHqaeUCN00nYJnps9W+GZ37xVadhrm4FwxcoiWjmJJISOO716awrUf8kTFIPxjay6yBDCLoX4GZJnGEoqCl1GDPTdjwnEQEDWNIHD8xAylTsfH74lSdp3QJ6VGpjAgUnN21Q1N9LGgVdmRWK/ICzmwK7RU7ZZRw2ERN3UcOVVlrrBuxRnBGZHtMacC0lLk1PruzsQ4E4LrAG8RJlWZ+9f+JosBohJeNcK6xx4y2veq2qOPECajc2RgTb2W+uBBIebGtfAMUVQFwYRNXrnKCzB1zhlOqqZFIUjA00afkzUo4MFoQpRPbkyKM2/HMS91/JZe4nXqK/74XtiK3/XdpVstgfSwFFAHyuD2PoZZkT9BcwojWJUKGGRhptqoDvwBsmgRlYoVXu+VZ7ZrWK7YUpcu0YMzHb7JTjE6a28oqOIQdHA3vTxZo4KJBiaLCm77REJkwX52TPn4l5tF7LW4YlvWa6J8EtjiBEY4Sah9hc5e25Reu2DRiB/rMRSDXmi3lbd9b6m0qyWA/ZPEAhH7usoaGyktDbCqy96xxQyZG+vhG746I0Zdb0d62sFQzMmSV2WVzGHxI6Udup07EPgL7Vddr6oMRiIXRcIUOgPxUkJkBVIu4ptTwrv0ubAg+yJCUorNwwkTd0jSAaoY/lbZY0vV0o405gNd+9klrVBPHxebD7xthEJdQHTf4Tb3AY2TUcvAipJEgpPim79upfSfrrY0bcgzIp8klqPhftfEzR
  template:
    metadata:
      name: bulwark-secrets
      namespace: bulwark-system
