apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bulwark-secrets
  namespace: bulwark-system
spec:
  encryptedData:
    SESSION_SECRET: AgBfLrFlTjReubGO4GSsew7rt2POt64hrXI3XZv5XMttAg5KyuAjuKxjxfiZMZPDqFxfeHtf5Hvn3B95KWqMa+OvBR09B5fzWJoLcFSF4Yw4071xJqbNgLAVAmPZLYvLFRGDDpwsYdsR9krYbJLNP+6dJmO3yKaIeAaN7Hh4SsH5MZsbGbhpe0YODW9ILkyMvGeRq6KLNaT7pbZ8hcsGBhMVRJm08OArcqlRsfHlegdxHcYL6uhbT4NDR9X2DFHff391sQhWtLtx0TN4Dz6WsbM3sEORZMfbZzmXn9xvC2+oG/uh7DP/psyjeLaY1Y9dT/zVyGJ3hdQyr0neMsWIVr1hy9KqHKItZrQtS8KaYUdiSFfXT228LhxHicgS+ZQDZTrRNvfm5CNs5D+GKkSa/51UxO+IdbUfAA2gsgrJAC4hTHM84nYzAqQ6FrE1c0mlMGgUNFldoCzdeRJ9/JhAvmYMTgnFv/Okojq62jAPX3ezJXRtR3HW/uNUHioCFOr++ZyBAdFPZPsjR8M6pVox/C65dTri/PSEThDfujT6eyjYAE5m9Wrk6Ba45RgGAxMzTKmXm+JHM0dtFIprjpC7OGPkZR9G3kQq94jJDZvQH7YjddEOKZD8fhCJNZZQgxO2x1WijE3oFBAvCFRUaHnXdjtI8Jbh2ZRgxgd5rOjjC5dCDyavz/qUeGRc7m1DT1oA3NAEUe6N1xs5kGR+LhN0VXplDFNfjye1F1hhhStKakKK5xR5SGTRRkV4fB0+fk8XW2nmXfjMPj9PQFd/EsfprAGa
  template:
    metadata:
      name: bulwark-secrets
      namespace: bulwark-system
