apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bulwark.namespace.yaml
  - bulwark.secret.yaml
  - bulwark.persistent-volume-claim.yaml
  - bulwark.deployment.yaml
  - bulwark.service.yaml
  - bulwark.ingress-route.yaml
