apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.30.0/cnpg-1.30.0.yaml
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.15.0/manifest.yaml
  - cloudnative-pg.cilium-network-policy.yaml
  - cnpg-instances-kube-apiserver.cilium-clusterwide-network-policy.yaml
