apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stalwart.namespace.yaml
  - stalwart.database.superuser.secret.yaml
  - stalwart.database.user.secret.yaml
  - stalwart.cloudflare.secret.yaml
  - stalwart.configurer.secret.yaml
  - stalwart.database.yaml
  - stalwart.backup-cleanup.yaml
  - stalwart.deployment.yaml
  - stalwart.egress-gateway.yaml
  - stalwart.cilium-network-policy.yaml
  - stalwart.web.service.yaml
  - stalwart.mail.service.yaml
  - stalwart.ingress-route.yaml
  - stalwart.configurer.job.yaml
configMapGenerator:
  - name: stalwart-config
    namespace: stalwart-system
    files:
      - config.json=stalwart.config.json
  - name: stalwart-plan
    namespace: stalwart-system
    files:
      - plan.ndjson=stalwart.plan.ndjson
