---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp-account
  namespace: stalwart-system
spec:
  encryptedData:
    GRAFANA_SMTP_PASSWORD: AgB5f5x8TxttaW6qUF4DptxT28cd4ix0jwokouLWnECQA+aJD4US+o5QiIkZhgp96tQSkic5GyLQONPc0JdmFEH7dFRD9eb25Uh/ImnTukFKSAOuic5lN8aH16LomyLoDeP+MSIRVYahP/VFI6SJBuAG4yzvZGEgcdeISJ04aNNlkLn+2UOUMw+N8drvgQz2qr1Sxgdn7sFSogkVBcn4HKrrGnh9IXECT2c/JKfAL/iiwkg+BZkbvYmVQN0ZYMmMYX/wLPfa1w1L0LzfbYKQzQ+4fBl/DD6Vy2zZZuOtle78Wrx++af28MvolNgsklxR9bguZNeA64rVnpyCq1ZeazrpNXN0iQ+JTyYELuL5b1u9/t++PHFe6LsvDle5rYgPYjYrlI+7tnnkF2f5GjsL4y56jViXghIC09BqgcAaP7vc48eZP/vLM29AFVLeLllTWI7o92qf9Cutjmd4km7HlUBNEtJM5cXW1Fd98fNafT6NWB3fug9DWAr/B+3epuJgSVrE43vQAPLG7UHn7zpzrd+Det4aVT/3BoZH2L41Vpf805Tvoj1iDdoNn4b44Oq/+ujvjWTSwCt6v5hhSFz0y0pf7+r1VwtIw2GnySHEfDbqwZ82u26wXC9pzzW5D1C7KX8Y5dfa5KpUd3DchuYhZhRWOz8NqCVdA+ZujhB1qiqi+S6g8BEEqiRgFHQUNB/9KR5MrojVkTNrqemyHcaVPcYojPxr5UMpjqfE+PJAo9zzo8jllzRR7l4PHKmztljJXIw=
  template:
    metadata:
      name: grafana-smtp-account
      namespace: stalwart-system
