apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: stalwart-database-backup-store
  namespace: stalwart-system
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://tinyrack-prod/clusters/public/apps/stalwart/database-17
    endpointURL: https://fsn1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: tinyrack-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: tinyrack-s3-secret
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: stalwart-database-cluster
  namespace: stalwart-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-standard-bookworm
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: stalwart-database-backup-store
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: longhorn-strict-local
      volumeMode: Filesystem
  externalClusters:
    - name: stalwart-database
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: stalwart-database-backup-store
          serverName: stalwart-database

  enableSuperuserAccess: true
  superuserSecret:
    name: stalwart-database-superuser-secret

  # 신규 클러스터 프로비저닝 시 주석 처리
  bootstrap:
    recovery:
      source: stalwart-database

  # bootstrap:
  #   initdb:
  #     database: stalwart
  #     owner: stalwart
  #     secret:
  #       name: stalwart-database-user-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: stalwart-backup
  namespace: stalwart-system
spec:
  schedule: "0 0 */4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: stalwart-database-cluster
