apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-configurer
  namespace: stalwart-system
spec:
  encryptedData:
    api-token: AgAy3pukL6W/XzZ+LujxBPn5mwwcI086dNhjWTFjpSLmSr+tEOppfctjNa3JoCLCI5LHDH62504wJEd+cUjpZHYh9jQgnYVdFpwutLKCT8tMSFdHPVjaH4opUDEqMOJMaBzATNP+qh+Z0Z45yze/665YEY78pyz7qvMZx8vP4sNfyfqiAq6MzGeH522tGO55jN8aYtPvqdH1O2MoUQCN3XglpRgdFBcsbA+0pVm4jowkz+hutE+mw/aD70mOZT4GXVzMQQ80LBxz22DvLbmPToeQ29jGU4EtB7up0+HqRDcI9H/lMMWfRXSrSP5X/iVA++rKNauukj1mIIaVJdOjnreAe02f6wECUe8ku3wBNAY+5/aYe2zgnEQsiR3vfWjSI9AIqsIs5/XNauKdHHAjdLDRrTtfB8J7jtvKbZfrNsIm5c5OL0hHGlUhZX69Vk1nGpwP/LLxRIobKbR6BfszkvVtGnKh616SZmE8fuWUzuYSwU9KxkZ78fvf/B/QaAOV+/IqoiUzqD+xLNXAm01p/ONYsJMl5KPUNfl7nnlSnjidlieD91svZhT5CyvPAxmo8wwGvFca8zQir60qEpj4BXjPJZH2bYasYYeUbSB9mKnpsJpMykARCjfXyOa+WZiGyZqu69hTxmjT6iRXtQycO1KJbOzseuPOtqpPMFpyDN8WMP2/3KAGOTL9hr539siO5abEkbN7hTsYyNC6FzhEIIv1g0R8p2VA9B6m2FiRKWc7P9P7a/2PJ5dPecU=
  template:
    metadata:
      name: stalwart-configurer
      namespace: stalwart-system
    type: Opaque
