apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-cloudflare-dns
  namespace: stalwart-system
spec:
  encryptedData:
    api-token: AgChixTvqCNOLwe+7BGmtU0Vx/eivxPaGjgVLY5kLgWm7fjLGYD/E7WpazoEZyIFoT9GjWv0Mk2MaNS4Pw3I9ksQsIouXwTz/Urj+UUn/YzE/ELZRqEMRhDfPqWqzmZUA5nv/j/uYuuU0qE/iMvaxBoBiSVSwYQoHK4zL9Cfo7LhECwAhxezwOJC5FttehgVlLK7XAOVvD9Whc7A66nl1k3q8K8I7B/ApodVlNUocARpoWKoAZ5+qjZm31RycPvOuKJZuTJUqqmr3jY2JbQoNzBCTuH1JUtRuwfroRu1I0BLoTFObl6LU7KivOI2eOzM2jwAEJV07FGm09K3c0BKj7Lrc5lVCiD2NvPS95z75CiBQGqA6ixUY0hmGS/o86BTCLcP92WjKf0nQlNOuwIeAjTJHDbRModMlPSZXuYC+qYimSLPq4+HRliqsvxIfAwrttp7yFye59hRS9Jf7QLd4JqVB4rmZkY3UfyEEiPoYCMND+ivdFs+5B1qQ2JwChsHWwXC0VV33m/oLlnw4ShdNIWKwkKc2grkg8a11G1Ak9OTB4sBHfc5SlMp0NhXzZ2kE6kd7WXE/sPgdFZudpF56GW/OeF1pFgE2ORScEJ7dwOK0V44YXCCW5fzmH9azDDaAQvP5KsaAHKtFuINR+VPDbZ0KXDeSKYi2KBfjdqii8zDWOi9cr3YRsRVB1EIn2tLe4IDsMGH8TuLDRsq+QksLddzrc35BKuzrRrutsLI9aFFcnA4POFwJJ4uveS/iEjWYfi9PgYhAkM=
  template:
    metadata:
      name: stalwart-cloudflare-dns
      namespace: stalwart-system
    type: Opaque
