apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-cloudflare-dns
  namespace: stalwart-system
spec:
  encryptedData:
    api-token: AgAzU66aCCGEk9G0ltJ/PDy2p+Esmh9nerkbKvKZg9PFgh/DdCNIdVjsMnurXMTdEAaErC4xYs45/l4eTw04WOcfFR55xa1whWQ2kl4+L2gtp6jRcLPHP4VtQbxm1dfKbolmFjVr9Q0N7O+kWptsfKTVAu71yUpE5eXx5i4vSNYzCvU9adyv2leSm4f5jvn3pYYZ6URGkry1wXQnTEh6vmCFiBFkidRTe0y5hAemKBmP6myTCCeW1Qj3hiE33CS4Ojv4McvSYtTy4DjiyWuQJEKOTqzz53WqS+TtKaGItuUcNjdo5CEuG8cxXAHK6Xk4t+23IRI3DC/x00WqCI8Vk4e1hQ6IVivm+htXOAsMVY9fG6qaoAg1Po7GAKXsCLZti1UfyKs/EAA3vD9SBqZaoGBI0kNl4a9Ckz2/dEvM+UAZYLoUTEkX9pru4aoQ6ZiBP4Q5tBemr1EAU5QTDaiuP5j7OyrcIVCzBpF5tJYwBTzpHgQiWG1tZu1GkY05UWpz8n7OaboHvoCstqyYVggleFXY0B/NloPDvfwmahHX+PqxeEWzfNfRGnYVS6C90vknceYTTR7sL0VJ71/du13uGyANJ074oqgd24V5WWKYD1/iZGhmtQkc6nSLFSTBtiQtLenQy9wMCaejcsCRq3l9khYSPTO5T/ApWtXV1e+Jv1M6ysta9hnmZbjJ2KMGK/Tn0RVNdLTbNZ8wrmk449rkT1Mj5qhvGaS/g37Q8fNF17cq4WHiY0Jn/s9IDbCsUwOdMK4CaR6OyzI=
  template:
    metadata:
      name: stalwart-cloudflare-dns
      namespace: stalwart-system
    type: Opaque
