apiVersion: v1
kind: ConfigMap
metadata:
  name: stalwart-config
  namespace: stalwart-system
data:
  config.json: |
    {
      "@type": "PostgreSql",
      "host": "stalwart-database-cluster-rw.stalwart-system.svc.cluster.local",
      "port": 5432,
      "database": "stalwart",
      "authUsername": "stalwart",
      "authSecret": { "@type": "Value", "secret": "<rendered-from-stalwart-database-user-secret>" },
      "useTls": false,
      "allowInvalidCerts": false,
      "timeout": 15000,
      "poolMaxConnections": 10
    }
