apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stalwart-ingress-route-http
  namespace: stalwart-system
spec:
  entryPoints:
    - web
  routes:
    - match: >-
        Host(`mail.winetree94.com`) ||
        Host(`autoconfig.winetree94.com`) ||
        Host(`autodiscover.winetree94.com`) ||
        Host(`mta-sts.winetree94.com`) ||
        Host(`mail.tinyrack.net`) ||
        Host(`autoconfig.tinyrack.net`) ||
        Host(`autodiscover.tinyrack.net`) ||
        Host(`mta-sts.tinyrack.net`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: stalwart-web-service
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: stalwart-ingress-route-https
  namespace: stalwart-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: >-
        HostSNI(`mail.winetree94.com`) ||
        HostSNI(`autoconfig.winetree94.com`) ||
        HostSNI(`autodiscover.winetree94.com`) ||
        HostSNI(`mta-sts.winetree94.com`) ||
        HostSNI(`mail.tinyrack.net`) ||
        HostSNI(`autoconfig.tinyrack.net`) ||
        HostSNI(`autodiscover.tinyrack.net`) ||
        HostSNI(`mta-sts.tinyrack.net`)
      services:
        - name: stalwart-web-service
          port: https
          serversTransport: stalwart-proxy-protocol
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransportTCP
metadata:
  name: stalwart-proxy-protocol
  namespace: stalwart-system
spec:
  proxyProtocol:
    version: 2
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: stalwart-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
