apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-cloudflare-dns
  namespace: stalwart-system
spec:
  encryptedData:
    api-token: AgCOWwm9eyev2xAlfOMladqM4JnHrvx88e/dSgdK0coBlyvkd+aB8xjeK9dYz7TwsmN1N8AR4ant4kGScw+7TybqlsvGnM6Ju5TcsVj1EiSBgPTmMuEQBwTqoV16B2JbXOKMkTxrwgG8J077VokWbBfnjlbSQ5pW/SvTae7Pr3D3FLsLWj2rLYj1k//wdPZ/q/Z6yIpznDKQzVk5zyuxItrAzTx7zsJaVWLYuaIySWXK+Y1Th8j3SSGb+GJZRarpUWFZsFV+5ecbeTyMtqgJJVwmIWYkdN4PD6InADPO6wrYongfAy2/LhVbeVKCNOrs9I23QkssDHlyWYENWPq1QPMDNC0Wlvd3XWNxOscwRUpuUYtXqH/z/wP9YB9TQTtmgQV+OLCssRMqs/EtsSogXeId3TwC/ynCFX+3RRkNcLaTkzHTv5aDQ1ELD9ZezXZj4x18UWkoUYH3JuvcN+e1BMCT5fRoQrXVyhOONHyrgmgnnjQtzJccymNytCP8YCJt7Li2NUaoyH9PssP4GAGk+Ft5rYNaA5EGlyFRJ2Y5lp/xzobz3REC0VUqzDax2DQSQPxYzw303SoK2RFWkILZGYRvP74CF7hrRBAW88eP4YdWzLM0viSnqkIe66IQzgpoU9bmFzImXsKbojDuWbBPn6MNe8B8GOXjzzeCA8kHdKsdhmW5c4ZUNvoeXs1zg5fzByca9XbOkzaFkjeNF4+NcBGfZaHBphIo4SFiiOd2O5FTiM2jc3ko2fTjFB1w5ciTBykTqhPv9A==
  template:
    metadata:
      name: stalwart-cloudflare-dns
      namespace: stalwart-system
    type: Opaque
