---
configure_stalwart_api_url: https://mail.winetree94.com/jmap
configure_stalwart_api_key: "{{ vault_stalwart_api_key }}"
configure_stalwart_registry_account_id: e
configure_stalwart_cloudflare_environment_variable: STALWART_CLOUDFLARE_API_TOKEN
configure_stalwart_acme_directory: https://acme-v02.api.letsencrypt.org/directory
configure_stalwart_acme_contact: mailto:admin@winetree94.com
configure_stalwart_acme_renew_before: R23
configure_stalwart_acme_max_retries: 10
configure_stalwart_dns_server_description: Cloudflare DNS for ACME DNS-01
configure_stalwart_https_listener_name: https
configure_stalwart_https_proxy_trusted_networks:
  10.57.0.0/24: true
configure_stalwart_http_response_headers:
  Access-Control-Allow-Origin: https://webmail.winetree94.com
  Access-Control-Allow-Methods: GET, POST, OPTIONS
  Access-Control-Allow-Headers: Authorization, Content-Type, Accept, X-Requested-With
  Access-Control-Max-Age: "86400"
  Vary: Origin
configure_stalwart_domains:
  winetree94.com:
    id: c
    subject_alternative_names:
      winetree94.com: true
      mail: true
      autoconfig: true
      autodiscover: true
      mta-sts: true
  tinyrack.net:
    id: b
    subject_alternative_names:
      tinyrack.net: true
      mail: true
      autoconfig: true
      autodiscover: true
      mta-sts: true
configure_stalwart_listener_ids:
  smtp: iqwuqve1aeqb
  submission: iqwuqvfeafab
  submissions: iqwuqvfiafqb
  imap: iqwuqvfmagab
  imaptls: iqwuqvfqagqb
  pop3: iqwuqvfwahab
  pop3s: iqwuqvf2ahqb
  sieve: iqwuqvgcaiab
