apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-install
  namespace: flux-system
spec:
  interval: 15m
  path: ./flux/infrastructure/base/cert-manager/install
  prune: true
  timeout: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
