apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.namespace.yaml
  - sealed-secrets.helm-release.yaml
  - sealed-secrets.cilium-network-policy.yaml
configMapGenerator:
  - name: sealed-secrets-values
    namespace: sealed-secrets
    files:
      - values.yaml=sealed-secrets.values.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
