---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: kube-prometheus-stack-system
spec:
  encryptedData:
    bot_token: AgBh7POcHm+8NIkKSmpKtruKin2AVTcMRjx2C9XBAHJ7YPBBsNY+SduBbjTFfUd7YmqEJHuOMDyauHNhcWfBdRgvL6vcluH+wCHzhG3H7Z7fJuzEqMQX964tgfA01PMi2u2T+x5sjpl2fdt+6vEVI/QyRJrw346mCYIBRCXmWfj5nsD1Kzj0tkBysG4TN6+xpWR7CalJtdVqu3Z1V7zyo2KgkdjPcDCub6m/yKXAg3iL3gsl9+EJ/fd6ikH/tqd3Me0fwvHhBMULqsWlg7J+qzvnmUEbkmlcgWba406nkLGeQ6ZpRJLGWVxvIZxqd2jKE6YKOZIcHdaX5pomKYkVINKE9qTI7W3hGFhHT3igWg7OL+VvUA7BU78QUKUMhhfnsKCG6vd6J2R96Ur6dDSCSl0dqyc+rD1sgJTbaUmyCZ2n4bSNU4JTwF9smHgv/oi/3sf0uzabkADzM9iM9u8YmIowEAs22zKpWt6dYkHQQnTaN0aG9kDAYEMD5MatGNtjMjVX8if/McmaMU8Nsc8eMXJTRP2/0LgSvuZAI3YBJdlRxmc3oz/U86LuCjM3KcayCk4BT1Pgf58jbmuvk6ZbBhOGda4rxb0tEzqoEwAuYQFkIXnV1BAeKpPzdxXUfYotTgeYO+N8yOeEFcATj6B1oh1QSl8q23fu8a5Q2ODGAyN/iJlMS9dUCXbCtKq+ZYY96LZlnmAdQWACEPQOsosp5QUWkEx/YYTBu/ZL5i28dcsndrmWJo3lVIDvwcEWL7Kw
  template:
    metadata:
      name: alertmanager-telegram
      namespace: kube-prometheus-stack-system
    type: Opaque
