apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack.namespace.yaml
  - alertmanager-telegram.sealedsecret.yaml
  - kube-prometheus-stack.helm-release.yaml
