apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- flux-system.cilium-network-policy.yaml
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: allow-egress
      namespace: flux-system
    path: allow-egress.network-policy.patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: allow-scraping
      namespace: flux-system
    path: allow-scraping.network-policy.patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: allow-webhooks
      namespace: flux-system
    path: allow-webhooks.network-policy.patch.yaml
