{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-s3-secret",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-s3-secret",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgASOUv9mVqmVzvsSVy8FmwKyC0LcJdwFUEzdKylfpwO+hIBdJ/xPdBrZI5X6qLyD+LrdTsBn1+EbD2gSVVFkJF+PbL8LJdiLEHGI8BXNkAcoKVNu608GAwxIwtma1hWCYlcRv3o7/Rit9oZ2fxPIwtrSJalxa1WoNdWl4ORKADnJBBhecitznBwBNJvoBhTH7n1r2FcIBXkTArmvkH9h99lDdaY4E8ewzO2bpy0p/gCZG63dYfMRwuA/PDnsH0NQWaMjmOYck5l3oarTVm4BAXIovt65llqSl2HnHDeqX+lFx/jotCWKSTTn9v7rFKbONjNl+wZi6zjqe7mqFC8Juy5VSHAVAhtdxDPCJerlRiQPx7NpjqgEY8PkvW/WrZIU5ruZXKlzoBtl+Heq/QKSu7eyyjRzjhxnX3LqmBTa4rvUozVZkR+CBkqdnYiEvnrJwluw9FCoZROplb4rx65zEmCbUwAbLDPNzQi/XAo0307RhyBbSf7EOxpwfIWIRr4bWVV0onzOvQCNDL45o6KdO+TiWZA4BkBSAT/2zYZ/iR1YPkVLpHk7SG89H6qMfjvTPywJUlsU7hJa91DAeoR6YJPgQZ0CdiHj8CD7pZTCKBACdev93I365jFIxdB2DyUvsQ/r+CPxb55f0Kx0xaGXiRidzRhNaspPOUvtoEM1kyZnPTxHmFqhbGe0T6w4ak2et9UNpal/rkthx8HFq+mKEudabu+4Q==",
      "AWS_ENDPOINTS": "AgCusVd8pxfzrN2//ruppJeyoO0DfAVq/fxqH7m7kPjGjLE7acUp7IoEaDMhXh9gK4vl4bRALlPCJfodks73Li12wQvPmmkpbw3g3DH3yb6AoxunrZ0ceuoja5kbqIDoogq2ZVuUWSMmt5/DjOwrp05UurPpjMYcGatDirkP/Hb2P4sF0XjcTHi370y4S1aGBfPopTQWfKRTMi0W5w1XwM3eV3hN0TiaNfHasI/fuhKaRfvfHZOR1lUjYZgrLr3s92X/S5uXjLQ0X+SRL3sG05CxUtW3jiTSTrmCqaRu7uF3H9UsQlkk40IbMax2TlFLGgLOI7SQHVS2qWTf9b3NR7u/4FHW7+1HgPwRR7wKWUalrOqzL8DIzTs2ef6cfYqSPFlhXibIXPwNPweyFjvA5s2AxCAiXIWqNmkZIq7ik1z35D8TfAjqKMB//8wO3pk4QTNJ7pYJhf/QFWY+1j9CZGXRCXdRf/EulTWpgUpmP82VBbBOtnnjM/pdQwI4mseMKcZ63awD6xAsv5rjOLmt+NFgOF5YVKtHxbmEtEwSAYWxzEUFlitGChOxnmwh9b3+re7WEyVCk6msP1eHP+lmNcG/CDrOdPhwd1JvhXy5zJjPEkD/kgBqAQtIucqDHJXgDTkSq1KmlVL7NRnQmWjLG4CIP+jstHP9qShyUXVeaD6bPR+gfUNZrrefiPA1VsQim50q0AssGMJ63+wUm5HliSWnA76N6/RWmPEDZUVNng5f0kOYug==",
      "AWS_SECRET_ACCESS_KEY": "AgB2r59cowyUsKwEcaku1bwD59CSCo5j/2hcLqm7llMypkljqfWbTV2LfOINFb19Z3fLN0PZ1mHR6mtnoIZJqeqjinLbEliEXmCYk1nCkP+8wGY+w2zok5CUKLOP7KEh7g4WLjK2W1y5DUFnZWU9YDXMeuLQD1GBfA5ni5V8Rc4Dthfc/techan3gLQq7uMQRektZ8INngnW2gPo9pz+NBV/48FN9PH/eFvUU1dUtQHk/R4yAWaH9ht/sMg1Qmcpcl3MixmB+9rc1s6Ve/ZsWMbi0tD+ofX8sEL0VkkJaWFjTPmFkC4N9zFEIPr8eVPNwSLmRv72MsFIFhA/mhBgfcuErL355xpjstzEoV0t1o+4TP1H/VjupgnByZTSWDBNrCjKsYhq6dgCHIHWgDnmP0pB8HxjGmtEI+0FEw+frtBNOEsmoM8HIs4EessmHnqNWpdfHuG0snfZBhq8V5KP2iIyNKxJf4ICKqKLQ8Bh+p7PYQCsTua2D0uMBR7KlRBq6a1Q2+DHlaXkRNJHOPh42uDt7cZ3qUZtv72kRRunaUqz+Mkm/nAl0+WaY3Gb+1n1ANBq3VBEoBvXz8h7fgPip1Cz06HgB6erVuLb0kpm0pyHRFYqDcsYoTfzx7y7o93Kn36/krhnMkNmd5Hg12yixIMjYsNaTly6HFDHdTcdKMz+IbfZt+IXDTJazRTkWLwv9n7JGMYvxH/OqmlvrbYlUGN9hwyZwuBgvCnjXYlXmOPd/B+ahpMGTGMF"
    }
  }
}
