{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-s3-secret",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-s3-secret",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgAZfBs3mep2DnyiAUfT5jIovJ5Voxqqx+ls7jyMnroTUett5Ho7TDWRwVA+VWGKrA/Y7mEzPmYG0+X5ElEkEmpYKNQKZnQql2mNcaRY6a/EWTBjId7KZ8coVD62Ja+QMVr+lgIMSP1h9Ua3du8yJ9JPp7f4AGnwsXYk99xcYMKNgQHf0NDQ0DaydtC3H/eFdIvierTPDKCMkMRJuideiOimKPCYU03il+98yBYTA/wM5/WLBaNi+b9zC9GldNMdI8TCrFTcoiw2XRQBS1IPDyWHyq1ZBOaWmcdVOGRHB+HK7phxmcZnHjjH5mcUlBj26eMARBelrBoIl0i+xvUE8zDu5mXpASXPQXSopDO6K+Gtxp4/pKcR9WjCfhOagkpkdp8E0fy2jclwt7FpGXE31wniBPtKWoBMkms6QTlvAxvYVtsAnelbPiIW5/bZQm79pKStehtdW1lUUBbSkwVG6YBa1NxORpEFKOac9piRltSmsNsCzzrCoQFDyTUSUotF5GmpIZfJzHccfjIH7W90Z4xzzG7oc6KIb95k2YsYN1yf7AolOxJBUJbYLi0tgHYNveVvSOsV8tYgGZEj8FotWjgFpZL/48wHhg71RqvYNQxpe/Bh/Y8ka4vdhNRltvunMZczUCLMpUkyiTwV3eQ0wYIGL10rNqXcyeMhawRSGuOljX3G3jGR17Q2jLqQgZlVNaiBElWFzlrbbNqtO5RAo/6KuXYHQQ==",
      "AWS_ENDPOINTS": "AgCYJXYN4k/JpSY+52JieImA0J78Tqn1ee3rnbuBmEjmdwah2OrO3NFZdhWMKVi+siFxO+MVSFVdC52S3MDD7NgbhELmP6rTTCgH9MQkMtBvz6eMFDAiq+YredPDweSzcCul8fFjuWhqboPpd7kYLmdVpL7t/8xDImMTNRzKSgCBirR+GhYHrgQPHl3cgryr5XcQTmL6cS7SgSsUj31eN3BAfcqkj7oZ4X4NIQ3l2NoV5QDVgpkl4uHcwk8RziSmGhXkM9c8uRS3AdONUabTgH7+sasEpDoJxTLpboSszhHqU7SDYduWU8TLYMgiBFtaQlHH6cVFQNd2K0IUbWZIQU5z+C8c5v2qRLvxvlVuZdLExdFx8Yow/ArXTZYn6RJ5QI3bchbyFsYTD4sTy8G/U9CmaBu4cPSgOMMNdCZeMaL2I8jwuy90OiFQd4cVUt+5uA+KUKGO2K1cgaLkz5Irm392uSMm0SsyOzGzQGYyAjpurSkE7WSDdnckQ/fgOcYC6s8Hi0wh60m8rQkapuJjfzczq2QyGguC4kWjCvdoXQx/pIh3tF6gg2Iglm474VGiblQ7W689WSuaTJ+V/yf/UtIxKIDT/xqd5iKvwxdJjHzRZbNC46C3LT9xakpuHThxrBeF4vdvfX3VtdeQCrpr5b9IZTFQdWz+474wLCeXPhqjd8t6xXLGPP5HAi8TF7e4C+LkAIYKEXN1JFnIu0oO4VAk7ZQKtfFrLYdvoGw1MeFQZDcpRw==",
      "AWS_SECRET_ACCESS_KEY": "AgBprtMUYk6UKYkygGo2HlmXqR5MqlbI+0vJg00gm6+bFkCtrRZpGNkyc9jPhQdopFdbKSYEha9CGYTMZnwM29batjipBC1qF2MVFx9+5abmCnIVgMqle9S8edSp/tEPFxo850u8T/ncO/Um9zJ0231jkBUbCx6ykW+uWrueHuYX3THboBoUckRSjoxO0glRXu9pdMkoRdBmmwKrloTNJRL5cYsh5WL5+SzMnHEhZmVbZ3qLRiyJwxVkhA0HdXSOv4YijAWv9HCohBZo/5RBOsUqoP7Z33RzkyoqT5Vk+3qyvTQUvliwiAeLDmZakhdX21l4jAXkXBD+9fKmkVOYO/p4hHeXgK94xXhPCEkIZ1e6XVbQp0BunqKs8pF5bJopDzDSvkTbXYRAAiUbDK6s7JwMKTJycJHHXVOFLG/vm99GQOtd0vj6eltXLlBIRwSFaYqldFPnoEGZM3mRgi1LyYQeTthtpXFcs5nmc7pjSWCwvXtl92aWrFd4Ne5ZU23QWQtwwebm4TU4OfN6iKteWhzo87Vz1kJhi+fbVAlVbPMoTAm/lf/bN34ta87puEj2KcOZt6RS0MAEF4J+K3hqcWsPKifwhKqoDnSyOvwQuySIzaxzR0WHpUz4IrQ15yGuBw7f8huriwrlRoDzibIkUZqyrQ/Qic8KL56qzx8/9PICfPWUzGupnli6cKe4vmz3HgjjFSiUe7LAB7FS6t7PLimKztl/Nfrx2CkdLblJdIaGNHP/ZmRvKwWg"
    }
  }
}
