{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "stalwart-secret",
    "namespace": "stalwart-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "stalwart-secret",
        "namespace": "stalwart-system",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "admin-secret": "AgByloniNbaqpPZmkcr4uY8+VP8cAhbulJvY4tkRI9BNCCh++APhN3ZJiEGnjgAWbrYF9sG9HqEh687c6wHJgOWYJPntHkTx2D67AjUFY2Im0WNaWunTSqPzLganrINEFjSmNJ/JLtH9u4M1QS7ePHZdOn8Q+N0m+3YHcOn+0Qd5Q6yyGVmH0GWXU5fhMPTQ8qH1p/1Cu0qFaDMwehjV3Yl2ajqRHwf4iUiDi09qu5+Hnk0WG6/vz4GWjb9suJUKXR262OOWHaFt4aJad3L4vrXutZN7k4VXUqmzg/LoYIIn8oOFzOtWBVHaeit3zFbZNVgI6dn+w3asjUP7jO+6GiSrQKQDH7v6v9nedBdO87ARt/Gq7BEA9HhZMZ2jxCU/fUpBt0ZdqiYhyXDzsHblv+TbftzQIevh7CxAHIdpXOlY6rfXVxhGlGqre+YFc1/BoRVZCPFK2zccQ1X1A4fDWWiRjcQpkCGiI5mQ3SPCa0iSxgXvbQ4AXGDHP0Qr3n93FVHekdItWQALFM1nCD1KSeEOlPQxnVbEW5B8n5Mnn5d0uCMXgEaxauUwmzd+Dluko62tARZKBsBHoTEIoiUZX185U/emHXXmqXHSL+EEO+mVgJOuwNA4pfQ8m4VO8ksB/gDa6ZAR+S7dl46WcGM2uSijSMxrUxu8xHMmsswrvseUDGsfs1W+OQoNtuWXuXICRHhsbOBJWM9VLmn0iEaBrGeplgrUbn9G975UeepNyeCOH/4+MllVKd9KqaSm2zbZmR4dgBUJTODp3V2X5taXalD3jRU9WziFHqn1oYUuoK1ntKgF3kOzs7jOaG7NMHKBtGj6Bjb25utHm3EW",
      "admin-username": "AgAv5dPEdx5e1jO+UZTN8kJHZhidFYam36FrGtbK6yEwSou8OL7Z0uAuUEA+5dTVyIAzFaaYnI8b7VA4+anMnKERBonrg7D3EBE2PnYI5gebiG+26IFEsHTCjzRSMfGvyRPDlROUtwCUsoyS/vDH05m6BuvJxNyGG1753MZvG7/YrdK80nI38dP5Ez8jk74LdU5ZnY5drN6gepyhs0xdmSDvxFJw2hYYPaI5URuiypipVLB/CnxJzzDDOkozzaRlw4d7PAwTvnpGwUhWsEcMN5YG4yT5oq1XmR9QD+M2eCGYaQw6WcrdYhOxdbh1oBZmqDFFUxFs/FeqM5JU8c+srWGmChvfGDRyQbMhmP2cJ0Y4xsgR6GTu3I0JPrzjfjllgYCyCeT1hpIRmdArTy4Z9ntWgiEwa9ROv6wsdTlPIeXirlQUJDYiKee+eibdrZ5cwXdr0CvvRVwxbZqDqVENO52ndy9Nm7pPAGdStLnTYyfrRkpQ7ttxDEY7gck2H8cHaQO6msQL6Ri4tMUjbIIdKyIYVALdwhCoTG56Z52bn/+30lxDA/aCaMuDF124qNmrrQW3lHB6gEeVA+v9wylxMoU0shDyXgI2NXiODDKmar8d5uWacFfCtYbXSoAVjDlIe6Ct0Onbs1tfywY32HxkRSr7UOYqlf1Jo0kG4KV4zeahjUOWZnBYRQFW7L9kb+msVAMxk6KiLzQp90JuMg=="
    }
  }
}
