apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stalwart-storage
  namespace: stalwart-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn-rwx
  volumeName: stalwart-storage-pv