apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring.namespace.yaml
  - monitoring.kube-state-metrics.helm-release.yaml
  - monitoring.alloy.pvc.yaml
  - monitoring.alloy.helm-release.yaml
  - monitoring.cilium-network-policy.yaml
  - monitoring.telemetry.secret.yaml
