prometheus:
  monitor:
    enabled: true
    interval: 30s
    relabelings:
      - action: replace
        sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: instance
      - action: replace
        replacement: node-exporter
        targetLabel: job
resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
