---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telemetry-credentials
  namespace: monitoring-system
spec:
  encryptedData:
    TELEMETRY_TOKEN: AgBaFPH8Vt2ZB/FTd4PHTa/3GRQqIJjEXVpBNVqhyuD7RseZ9Jf6TTLJzgJwIAPRxM0riU8+N2gXniwGBPbkAnnxR/TOUv0VAF4T7IgP7UzsY2Q1a4tCwacW3N0CgkqCJY+f70Slhrg68eszH3CsQesM/3xKuYZ0JhPWcwlDYYzjlFloeWHhIdoYoNLiyem/ffzZthgNcymB9vE5w83Qd2IBQeTkQjfIkU40eWexExXO3uK4efi2HH2CF6yscI5NaMpM1eRipAx/TivXGq30ABnueGQXN1AzPmry8un8gcyasA0kAQb4HOFXqMeRxkRRjaic51fQcYARTQh36fECcitT52XkyGgt719vP+eb0f1e2ZNlHMQsP887/JDcMcHHzaOldNLUdzV7IIRuSxHjcTFzp50eKCoGvCKMV9sAalZVM0Ns/JilDoAeHqCweq4W2CKwiMYHsGdqQGgrprHvEPcYmvzkLYqvSzaC71O/0MJyrSv20FWj1CGqQOfZWV+LIw1B9HZwbgpsnUPdvl5q56vtYOody/wYfsYgfNAm0xecxBFXLLdrjeo89RbQrpHEoaNeMCclGiaIQtD90WmRG+dpImydLBHbZKa4ZVY8uZ4QtSJDWieRYmPmHuNcSL3E9XenY9gw1GiuE2ZjymLjo0NbnOSZ3jg+pitIZE643pXb4pyKRWItzsJfRJ7H2XULhY7I6MZxC72z4XxTjjiPks8ClgMfb7m7OT9Ix63Xdnio1R54gdw58K+Jp4WAgE5yw9TA0iqB3gK8pxjSc/dhmlw9
  template:
    metadata:
      name: telemetry-credentials
      namespace: monitoring-system
