apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alloy-data
  namespace: monitoring-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-strict-local
  resources:
    requests:
      storage: 2Gi
