prometheus:
  monitor:
    enabled: true
    jobLabel: app.kubernetes.io/name
    http:
      interval: 30s
      relabelings:
        - action: replace
          replacement: kube-state-metrics
          targetLabel: job
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 192Mi
