---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telemetry-credentials
  namespace: monitoring-system
spec:
  encryptedData:
    TELEMETRY_PASSWORD: AgBfMruWBu+jErIKVsslxBgkSUrmyU7892qpvRvKB7P6vtrSuTs7XbPFByo1HlzQwOBtY83lMbhnvGrAtnSt3EQADlf7Moi1n9Y3BK1jpRBjaDqjPLDkZiCa6yD0hd5smO7lkj7iwHz7RipVTT0mKSyOSFHkg3/589isUwJN7fvVV385Aah8OzxwWdR6r2ckno9HG0MM8D3BMBiH8GRs4AKv09Crmoacf+RTc7sxhupGb1yWtNLSYT1GanMWzDD8XahpJQGhWU+854sI+G3qY7DRbAwh+3fbtDk7b/6fGejYG51hlZ/x6Std1QzDMEknzr+OLNNk8AqUShxAMndPijtm5e4emIM/l2DPeQwY6al+te3pf+ymKCbsrcnXcBg+yp1vvN5pdFM66j76KJRS4IELTHxlCR1hWJWQmiJ5eRXFtvM2GqvzwFR7GCusflcza8cKUdc9zMDcH6HullMNMzXMXYJ97HRTAGymTdXWpFJSIa30IQDpm8Bb704z/Xu8fI+nt3UaSIUd6Nfm9xlAidT/5ZUoNilmN8yoNjbqewJi1UKfQCbiG6c8CPVRZrJJaTKT5AH+bjYfksqRZ7ww6eucHxoZE1xoq5EFJkfoe4Oy0XSWjLtvUna+D5dha/uUFL25BbIG5B27S8D5dkc1S4TIB01v3dD3CrCvD+U+leStOXDpW9Ji+JU3mrheikzCkFyR9It3OB/2hlIDfBwVIv//yrH9XRkQ2Biz2151s+f67pRpzFb9l66/VLrdyqQ48nc=
    TELEMETRY_USERNAME: AgBYRXl+EfrA9oyImbX8V2Ah5vNWNKW+UO0WpaR3+V5X2YpVXiUlvUi2S6ciKHMZWA/+eLgl5bbKiVE6nYDdBc2bkT3rEg7CCsASQ0X4eFf1Nc2r4TtGaayt1OzGhHCrGhF+grKY7WI5c5PFaQTshwB8/MJQuPFqBs0NTfA6qawKZd1TASXMx5DNc2W2Ozd0RzCSAPFW9ZBfew/5r3vwGpAgyBhSYZxUASKwd1H7wqjB0DY52EsibJ3aFidQctXCv6TZK7WtKZDRDOp6lq/VurIxRLuZlvc1KEucxbNPn/BjdhMouXPYipgvtWQ3/06xQHnHgl/zRW+Jn5Vy1fnj3a232eQZA5ZmjJzZs/0pzJlApv0cScAccjk6DrZJXLepI6sIjlI81xR4ysSsyPlpX/UUbvlGRE47waMV7U0GNxkVTC8H1LYcvnCOTBlqMm6q5j82lQUYwcwP4e3nWc4okAyfajmBDLrJrqUtrTGWyJbSOpDBAyyORedBsbWWFttPdYVejz1HTeZ2lHsADN8rbjucgvRqkrP2qI8dST2NtWBZCdI8/xfWx33gaLyXdOV+kCq21ge6rkkfC8D4zqR8lHU92ze+G0f5YlHADGFlYjE+2UwtJJ7VpXvzVvPAceMVMyIcOjrN+pxDa8B4jFTyPC4z2USEH64afYkzNQs3a5VLfjefW3irjs+OC1n9v1q01EQ5Xp7NUmiBXY3gXQ==
  template:
    metadata:
      name: telemetry-credentials
      namespace: monitoring-system
