apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring-alloy
  namespace: monitoring-system
spec:
  interval: 15m
  timeout: 5m
  releaseName: monitoring-alloy
  dependsOn:
    - name: monitoring-kube-state-metrics
  chart:
    spec:
      chart: alloy
      version: "1.12.1"
      sourceRef:
        kind: HelmRepository
        name: grafana-repository
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-alloy-values
      valuesKey: values.yaml
