apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-apiserver
  namespace: monitoring-system
spec:
  jobLabel: component
  namespaceSelector:
    matchNames: [default]
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
  endpoints:
    - port: https
      interval: 30s
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        serverName: kubernetes
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coredns
  namespace: monitoring-system
spec:
  namespaceSelector:
    matchNames: [kube-system]
  selector:
    matchLabels:
      k8s-app: kube-dns
  endpoints:
    - port: metrics
      interval: 30s
      relabelings:
        - action: replace
          replacement: coredns
          targetLabel: job
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy
  namespace: monitoring-system
spec:
  namespaceSelector:
    matchNames: [monitoring-system]
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  endpoints:
    - port: http-metrics
      interval: 30s
      relabelings:
        - action: replace
          replacement: alloy
          targetLabel: job
